adventureworks:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: yo11087.ca-central-1.aws

      # User/password auth
      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'

      role: accountadmin
      database: adventureworks
      warehouse: compute_wh
      schema: raw
      threads: 12
      client_session_keep_alive: False
