DEC_PROJECT2_BIGDATAETL:
  outputs:
    dev:
      account: qtkwtox-xm91574
      client_session_keep_alive: false
      database: dec_dvd_rental
      password: 2024@Sepnsp
      role: accountadmin
      schema: raw
      threads: 12
      type: snowflake
      user: suphineneo
      warehouse: large_wh
  target: dev

