DEC_PROJECT2_BIGDATAETL:
  outputs:
    dev:
      account: wc86749.ca-central-1.aws
      client_session_keep_alive: false
      database: dec_dvd_rental
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'
      role: accountadmin
      schema: raw
      threads: 12
      type: snowflake
      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      warehouse: DEC_PROJECT2_BIGDATAETL
  target: dev

