version: 2

sources:
  - name: dvd_rental
    database: dec_dvd_rental
    schema: raw
    tables:
      - name: actor
      - name: address
      - name: category
      - name: city
      - name: country
      - name: customer
      - name: film
      - name: film_actor
      - name: film_category
      - name: inventory
      - name: language
      - name: payment
      - name: rental
      - name: staff
      - name: store
